# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Rust

on:
  workflow_call:

permissions:
  contents: read

jobs:
  all-done:
    name: Rust All done
    # this is the job that should be marked as required on GitHub. It's the only one that'll reliably trigger
    # when any upstream fails: success
    # when all upstream skips: pass
    # when all upstream success: success
    # combination of upstream skip and success: success
    runs-on: ubuntu-slim
    needs: []
    if: |
      !cancelled()
    steps:
      - name: Fail!
        shell: bash
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
        run: |
          echo "One / more upstream failed or was cancelled. Failing job..."

          exit 1

      - name: Success!
        shell: bash
        run: |
          echo "Great success!"
